// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agency_schedules.sql

package db

import (
	"context"
	"database/sql"
)

const createAgencySchedule = `-- name: CreateAgencySchedule :one
INSERT INTO agency_schedules (
    id,
    office_id,
    agent_id,
    name,
    timezone,
    cron_expr,
    wake_event,
    enabled,
    last_fired_at,
    next_fire_at,
    metadata,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, office_id, agent_id, name, timezone, cron_expr, wake_event, enabled, last_fired_at, next_fire_at, metadata, updated_at, created_at
`

type CreateAgencyScheduleParams struct {
	ID          string         `json:"id"`
	OfficeID    string         `json:"office_id"`
	AgentID     sql.NullString `json:"agent_id"`
	Name        string         `json:"name"`
	Timezone    string         `json:"timezone"`
	CronExpr    string         `json:"cron_expr"`
	WakeEvent   string         `json:"wake_event"`
	Enabled     bool           `json:"enabled"`
	LastFiredAt sql.NullInt64  `json:"last_fired_at"`
	NextFireAt  sql.NullInt64  `json:"next_fire_at"`
	Metadata    string         `json:"metadata"`
}

func (q *Queries) CreateAgencySchedule(ctx context.Context, arg CreateAgencyScheduleParams) (AgencySchedule, error) {
	row := q.queryRow(ctx, nil, createAgencySchedule,
		arg.ID,
		arg.OfficeID,
		arg.AgentID,
		arg.Name,
		arg.Timezone,
		arg.CronExpr,
		arg.WakeEvent,
		arg.Enabled,
		arg.LastFiredAt,
		arg.NextFireAt,
		arg.Metadata,
	)
	var i AgencySchedule
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.Name,
		&i.Timezone,
		&i.CronExpr,
		&i.WakeEvent,
		&i.Enabled,
		&i.LastFiredAt,
		&i.NextFireAt,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgencyScheduleByID = `-- name: GetAgencyScheduleByID :one
SELECT id, office_id, agent_id, name, timezone, cron_expr, wake_event, enabled, last_fired_at, next_fire_at, metadata, updated_at, created_at
FROM agency_schedules
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgencyScheduleByID(ctx context.Context, id string) (AgencySchedule, error) {
	row := q.queryRow(ctx, nil, getAgencyScheduleByID, id)
	var i AgencySchedule
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.Name,
		&i.Timezone,
		&i.CronExpr,
		&i.WakeEvent,
		&i.Enabled,
		&i.LastFiredAt,
		&i.NextFireAt,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgencySchedulesByOffice = `-- name: ListAgencySchedulesByOffice :many
SELECT id, office_id, agent_id, name, timezone, cron_expr, wake_event, enabled, last_fired_at, next_fire_at, metadata, updated_at, created_at
FROM agency_schedules
WHERE office_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListAgencySchedulesByOffice(ctx context.Context, officeID string) ([]AgencySchedule, error) {
	rows, err := q.query(ctx, nil, listAgencySchedulesByOffice, officeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencySchedule{}
	for rows.Next() {
		var i AgencySchedule
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.AgentID,
			&i.Name,
			&i.Timezone,
			&i.CronExpr,
			&i.WakeEvent,
			&i.Enabled,
			&i.LastFiredAt,
			&i.NextFireAt,
			&i.Metadata,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueAgencySchedules = `-- name: ListDueAgencySchedules :many
SELECT id, office_id, agent_id, name, timezone, cron_expr, wake_event, enabled, last_fired_at, next_fire_at, metadata, updated_at, created_at
FROM agency_schedules
WHERE enabled = 1
  AND next_fire_at IS NOT NULL
  AND next_fire_at <= ?
ORDER BY next_fire_at ASC
`

func (q *Queries) ListDueAgencySchedules(ctx context.Context, nextFireAt int64) ([]AgencySchedule, error) {
	rows, err := q.query(ctx, nil, listDueAgencySchedules, nextFireAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencySchedule{}
	for rows.Next() {
		var i AgencySchedule
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.AgentID,
			&i.Name,
			&i.Timezone,
			&i.CronExpr,
			&i.WakeEvent,
			&i.Enabled,
			&i.LastFiredAt,
			&i.NextFireAt,
			&i.Metadata,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgencyScheduleFireTimes = `-- name: UpdateAgencyScheduleFireTimes :one
UPDATE agency_schedules
SET
    last_fired_at = ?,
    next_fire_at = ?,
    metadata = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, office_id, agent_id, name, timezone, cron_expr, wake_event, enabled, last_fired_at, next_fire_at, metadata, updated_at, created_at
`

type UpdateAgencyScheduleFireTimesParams struct {
	LastFiredAt sql.NullInt64 `json:"last_fired_at"`
	NextFireAt  sql.NullInt64 `json:"next_fire_at"`
	Metadata    string        `json:"metadata"`
	ID          string        `json:"id"`
}

func (q *Queries) UpdateAgencyScheduleFireTimes(ctx context.Context, arg UpdateAgencyScheduleFireTimesParams) (AgencySchedule, error) {
	row := q.queryRow(ctx, nil, updateAgencyScheduleFireTimes,
		arg.LastFiredAt,
		arg.NextFireAt,
		arg.Metadata,
		arg.ID,
	)
	var i AgencySchedule
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.Name,
		&i.Timezone,
		&i.CronExpr,
		&i.WakeEvent,
		&i.Enabled,
		&i.LastFiredAt,
		&i.NextFireAt,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
