// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agency_snapshots.sql

package db

import (
	"context"
	"database/sql"
)

const createAgencyContextSnapshot = `-- name: CreateAgencyContextSnapshot :one
INSERT INTO agency_context_snapshots (
    id,
    office_id,
    source_entry_id,
    snapshot_kind,
    payload,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) RETURNING id, office_id, source_entry_id, snapshot_kind, payload, created_at
`

type CreateAgencyContextSnapshotParams struct {
	ID            string         `json:"id"`
	OfficeID      string         `json:"office_id"`
	SourceEntryID sql.NullString `json:"source_entry_id"`
	SnapshotKind  string         `json:"snapshot_kind"`
	Payload       string         `json:"payload"`
}

func (q *Queries) CreateAgencyContextSnapshot(ctx context.Context, arg CreateAgencyContextSnapshotParams) (AgencyContextSnapshot, error) {
	row := q.queryRow(ctx, nil, createAgencyContextSnapshot,
		arg.ID,
		arg.OfficeID,
		arg.SourceEntryID,
		arg.SnapshotKind,
		arg.Payload,
	)
	var i AgencyContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.SourceEntryID,
		&i.SnapshotKind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getAgencyContextSnapshotByID = `-- name: GetAgencyContextSnapshotByID :one
SELECT id, office_id, source_entry_id, snapshot_kind, payload, created_at
FROM agency_context_snapshots
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgencyContextSnapshotByID(ctx context.Context, id string) (AgencyContextSnapshot, error) {
	row := q.queryRow(ctx, nil, getAgencyContextSnapshotByID, id)
	var i AgencyContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.SourceEntryID,
		&i.SnapshotKind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAgencyContextSnapshotByOffice = `-- name: GetLatestAgencyContextSnapshotByOffice :one
SELECT id, office_id, source_entry_id, snapshot_kind, payload, created_at
FROM agency_context_snapshots
WHERE office_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAgencyContextSnapshotByOffice(ctx context.Context, officeID string) (AgencyContextSnapshot, error) {
	row := q.queryRow(ctx, nil, getLatestAgencyContextSnapshotByOffice, officeID)
	var i AgencyContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.SourceEntryID,
		&i.SnapshotKind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listAgencyContextSnapshotsByOffice = `-- name: ListAgencyContextSnapshotsByOffice :many
SELECT id, office_id, source_entry_id, snapshot_kind, payload, created_at
FROM agency_context_snapshots
WHERE office_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAgencyContextSnapshotsByOffice(ctx context.Context, officeID string) ([]AgencyContextSnapshot, error) {
	rows, err := q.query(ctx, nil, listAgencyContextSnapshotsByOffice, officeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyContextSnapshot{}
	for rows.Next() {
		var i AgencyContextSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.SourceEntryID,
			&i.SnapshotKind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
