// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agency_signals.sql

package db

import (
	"context"
	"database/sql"
)

const createAgencyWakeSignal = `-- name: CreateAgencyWakeSignal :one
INSERT INTO agency_wake_signals (
    id,
    office_id,
    agent_id,
    schedule_id,
    signal_type,
    channel,
    payload,
    status,
    available_at,
    delivered_at,
    acknowledged_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) RETURNING id, office_id, agent_id, schedule_id, signal_type, channel, payload, status, available_at, delivered_at, acknowledged_at, created_at
`

type CreateAgencyWakeSignalParams struct {
	ID             string         `json:"id"`
	OfficeID       string         `json:"office_id"`
	AgentID        sql.NullString `json:"agent_id"`
	ScheduleID     sql.NullString `json:"schedule_id"`
	SignalType     string         `json:"signal_type"`
	Channel        string         `json:"channel"`
	Payload        string         `json:"payload"`
	Status         string         `json:"status"`
	AvailableAt    int64          `json:"available_at"`
	DeliveredAt    sql.NullInt64  `json:"delivered_at"`
	AcknowledgedAt sql.NullInt64  `json:"acknowledged_at"`
}

func (q *Queries) CreateAgencyWakeSignal(ctx context.Context, arg CreateAgencyWakeSignalParams) (AgencyWakeSignal, error) {
	row := q.queryRow(ctx, nil, createAgencyWakeSignal,
		arg.ID,
		arg.OfficeID,
		arg.AgentID,
		arg.ScheduleID,
		arg.SignalType,
		arg.Channel,
		arg.Payload,
		arg.Status,
		arg.AvailableAt,
		arg.DeliveredAt,
		arg.AcknowledgedAt,
	)
	var i AgencyWakeSignal
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.ScheduleID,
		&i.SignalType,
		&i.Channel,
		&i.Payload,
		&i.Status,
		&i.AvailableAt,
		&i.DeliveredAt,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgencyWakeSignalByID = `-- name: GetAgencyWakeSignalByID :one
SELECT id, office_id, agent_id, schedule_id, signal_type, channel, payload, status, available_at, delivered_at, acknowledged_at, created_at
FROM agency_wake_signals
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgencyWakeSignalByID(ctx context.Context, id string) (AgencyWakeSignal, error) {
	row := q.queryRow(ctx, nil, getAgencyWakeSignalByID, id)
	var i AgencyWakeSignal
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.ScheduleID,
		&i.SignalType,
		&i.Channel,
		&i.Payload,
		&i.Status,
		&i.AvailableAt,
		&i.DeliveredAt,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingAgencyWakeSignalsByOffice = `-- name: ListPendingAgencyWakeSignalsByOffice :many
SELECT id, office_id, agent_id, schedule_id, signal_type, channel, payload, status, available_at, delivered_at, acknowledged_at, created_at
FROM agency_wake_signals
WHERE office_id = ?
  AND status = 'pending'
  AND available_at <= ?
ORDER BY available_at ASC, created_at ASC
`

type ListPendingAgencyWakeSignalsByOfficeParams struct {
	OfficeID    string `json:"office_id"`
	AvailableAt int64  `json:"available_at"`
}

func (q *Queries) ListPendingAgencyWakeSignalsByOffice(ctx context.Context, arg ListPendingAgencyWakeSignalsByOfficeParams) ([]AgencyWakeSignal, error) {
	rows, err := q.query(ctx, nil, listPendingAgencyWakeSignalsByOffice, arg.OfficeID, arg.AvailableAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyWakeSignal{}
	for rows.Next() {
		var i AgencyWakeSignal
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.AgentID,
			&i.ScheduleID,
			&i.SignalType,
			&i.Channel,
			&i.Payload,
			&i.Status,
			&i.AvailableAt,
			&i.DeliveredAt,
			&i.AcknowledgedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAgencyWakeSignalsByAgent = `-- name: ListPendingAgencyWakeSignalsByAgent :many
SELECT id, office_id, agent_id, schedule_id, signal_type, channel, payload, status, available_at, delivered_at, acknowledged_at, created_at
FROM agency_wake_signals
WHERE agent_id = ?
  AND status = 'pending'
  AND available_at <= ?
ORDER BY available_at ASC, created_at ASC
`

type ListPendingAgencyWakeSignalsByAgentParams struct {
	AgentID      string `json:"agent_id"`
	AvailableAt  int64  `json:"available_at"`
}

func (q *Queries) ListPendingAgencyWakeSignalsByAgent(ctx context.Context, arg ListPendingAgencyWakeSignalsByAgentParams) ([]AgencyWakeSignal, error) {
	rows, err := q.query(ctx, nil, listPendingAgencyWakeSignalsByAgent, arg.AgentID, arg.AvailableAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyWakeSignal{}
	for rows.Next() {
		var i AgencyWakeSignal
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.AgentID,
			&i.ScheduleID,
			&i.SignalType,
			&i.Channel,
			&i.Payload,
			&i.Status,
			&i.AvailableAt,
			&i.DeliveredAt,
			&i.AcknowledgedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgencyWakeSignalDelivered = `-- name: MarkAgencyWakeSignalDelivered :one
UPDATE agency_wake_signals
SET
    status = 'delivered',
    delivered_at = ?,
    acknowledged_at = acknowledged_at
WHERE id = ?
RETURNING id, office_id, agent_id, schedule_id, signal_type, channel, payload, status, available_at, delivered_at, acknowledged_at, created_at
`

type MarkAgencyWakeSignalDeliveredParams struct {
	DeliveredAt sql.NullInt64 `json:"delivered_at"`
	ID          string        `json:"id"`
}

func (q *Queries) MarkAgencyWakeSignalDelivered(ctx context.Context, arg MarkAgencyWakeSignalDeliveredParams) (AgencyWakeSignal, error) {
	row := q.queryRow(ctx, nil, markAgencyWakeSignalDelivered, arg.DeliveredAt, arg.ID)
	var i AgencyWakeSignal
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.ScheduleID,
		&i.SignalType,
		&i.Channel,
		&i.Payload,
		&i.Status,
		&i.AvailableAt,
		&i.DeliveredAt,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}

const acknowledgeAgencyWakeSignal = `-- name: AcknowledgeAgencyWakeSignal :one
UPDATE agency_wake_signals
SET
    status = 'acknowledged',
    acknowledged_at = ?,
    delivered_at = COALESCE(delivered_at, ?)
WHERE id = ?
RETURNING id, office_id, agent_id, schedule_id, signal_type, channel, payload, status, available_at, delivered_at, acknowledged_at, created_at
`

type AcknowledgeAgencyWakeSignalParams struct {
	AcknowledgedAt sql.NullInt64 `json:"acknowledged_at"`
	DeliveredAt    sql.NullInt64 `json:"delivered_at"`
	ID             string        `json:"id"`
}

func (q *Queries) AcknowledgeAgencyWakeSignal(ctx context.Context, arg AcknowledgeAgencyWakeSignalParams) (AgencyWakeSignal, error) {
	row := q.queryRow(ctx, nil, acknowledgeAgencyWakeSignal, arg.AcknowledgedAt, arg.DeliveredAt, arg.ID)
	var i AgencyWakeSignal
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.ScheduleID,
		&i.SignalType,
		&i.Channel,
		&i.Payload,
		&i.Status,
		&i.AvailableAt,
		&i.DeliveredAt,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}
