// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agency_consensus.sql

package db

import "context"

const createAgencyConsensusVote = `-- name: CreateAgencyConsensusVote :one
INSERT INTO agency_consensus_votes (
    id,
    office_id,
    ledger_entry_id,
    agent_id,
    quorum_key,
    decision,
    rationale,
    weight,
    metadata,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) RETURNING id, office_id, ledger_entry_id, agent_id, quorum_key, decision, rationale, weight, metadata, created_at
`

type CreateAgencyConsensusVoteParams struct {
	ID            string `json:"id"`
	OfficeID      string `json:"office_id"`
	LedgerEntryID string `json:"ledger_entry_id"`
	AgentID       string `json:"agent_id"`
	QuorumKey     string `json:"quorum_key"`
	Decision      string `json:"decision"`
	Rationale     string `json:"rationale"`
	Weight        int64  `json:"weight"`
	Metadata      string `json:"metadata"`
}

func (q *Queries) CreateAgencyConsensusVote(ctx context.Context, arg CreateAgencyConsensusVoteParams) (AgencyConsensusVote, error) {
	row := q.queryRow(ctx, nil, createAgencyConsensusVote,
		arg.ID,
		arg.OfficeID,
		arg.LedgerEntryID,
		arg.AgentID,
		arg.QuorumKey,
		arg.Decision,
		arg.Rationale,
		arg.Weight,
		arg.Metadata,
	)
	var i AgencyConsensusVote
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.LedgerEntryID,
		&i.AgentID,
		&i.QuorumKey,
		&i.Decision,
		&i.Rationale,
		&i.Weight,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAgencyConsensusVoteByID = `-- name: GetAgencyConsensusVoteByID :one
SELECT id, office_id, ledger_entry_id, agent_id, quorum_key, decision, rationale, weight, metadata, created_at
FROM agency_consensus_votes
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgencyConsensusVoteByID(ctx context.Context, id string) (AgencyConsensusVote, error) {
	row := q.queryRow(ctx, nil, getAgencyConsensusVoteByID, id)
	var i AgencyConsensusVote
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.LedgerEntryID,
		&i.AgentID,
		&i.QuorumKey,
		&i.Decision,
		&i.Rationale,
		&i.Weight,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAgencyConsensusVotesByLedgerEntry = `-- name: ListAgencyConsensusVotesByLedgerEntry :many
SELECT id, office_id, ledger_entry_id, agent_id, quorum_key, decision, rationale, weight, metadata, created_at
FROM agency_consensus_votes
WHERE ledger_entry_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListAgencyConsensusVotesByLedgerEntry(ctx context.Context, ledgerEntryID string) ([]AgencyConsensusVote, error) {
	rows, err := q.query(ctx, nil, listAgencyConsensusVotesByLedgerEntry, ledgerEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyConsensusVote{}
	for rows.Next() {
		var i AgencyConsensusVote
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.LedgerEntryID,
			&i.AgentID,
			&i.QuorumKey,
			&i.Decision,
			&i.Rationale,
			&i.Weight,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgencyConsensusVotesByQuorum = `-- name: ListAgencyConsensusVotesByQuorum :many
SELECT id, office_id, ledger_entry_id, agent_id, quorum_key, decision, rationale, weight, metadata, created_at
FROM agency_consensus_votes
WHERE office_id = ?
  AND quorum_key = ?
ORDER BY created_at ASC
`

type ListAgencyConsensusVotesByQuorumParams struct {
	OfficeID  string `json:"office_id"`
	QuorumKey string `json:"quorum_key"`
}

func (q *Queries) ListAgencyConsensusVotesByQuorum(ctx context.Context, arg ListAgencyConsensusVotesByQuorumParams) ([]AgencyConsensusVote, error) {
	rows, err := q.query(ctx, nil, listAgencyConsensusVotesByQuorum, arg.OfficeID, arg.QuorumKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyConsensusVote{}
	for rows.Next() {
		var i AgencyConsensusVote
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.LedgerEntryID,
			&i.AgentID,
			&i.QuorumKey,
			&i.Decision,
			&i.Rationale,
			&i.Weight,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
