// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agency_constitutions.sql

package db

import "context"

const createAgencyConstitution = `-- name: CreateAgencyConstitution :one
INSERT INTO agency_constitutions (
    id,
    office_id,
    name,
    kind,
    is_active,
    org_intent,
    governance,
    role_specs,
    capability_packs,
    schedule_policy,
    metadata,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, office_id, name, kind, is_active, org_intent, governance, role_specs, capability_packs, schedule_policy, metadata, updated_at, created_at
`

type CreateAgencyConstitutionParams struct {
	ID              string `json:"id"`
	OfficeID        string `json:"office_id"`
	Name            string `json:"name"`
	Kind            string `json:"kind"`
	IsActive        bool   `json:"is_active"`
	OrgIntent       string `json:"org_intent"`
	Governance      string `json:"governance"`
	RoleSpecs       string `json:"role_specs"`
	CapabilityPacks string `json:"capability_packs"`
	SchedulePolicy  string `json:"schedule_policy"`
	Metadata        string `json:"metadata"`
}

func (q *Queries) CreateAgencyConstitution(ctx context.Context, arg CreateAgencyConstitutionParams) (AgencyConstitution, error) {
	row := q.queryRow(ctx, nil, createAgencyConstitution,
		arg.ID,
		arg.OfficeID,
		arg.Name,
		arg.Kind,
		arg.IsActive,
		arg.OrgIntent,
		arg.Governance,
		arg.RoleSpecs,
		arg.CapabilityPacks,
		arg.SchedulePolicy,
		arg.Metadata,
	)
	var i AgencyConstitution
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Kind,
		&i.IsActive,
		&i.OrgIntent,
		&i.Governance,
		&i.RoleSpecs,
		&i.CapabilityPacks,
		&i.SchedulePolicy,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgencyConstitutionByID = `-- name: GetAgencyConstitutionByID :one
SELECT id, office_id, name, kind, is_active, org_intent, governance, role_specs, capability_packs, schedule_policy, metadata, updated_at, created_at
FROM agency_constitutions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgencyConstitutionByID(ctx context.Context, id string) (AgencyConstitution, error) {
	row := q.queryRow(ctx, nil, getAgencyConstitutionByID, id)
	var i AgencyConstitution
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Kind,
		&i.IsActive,
		&i.OrgIntent,
		&i.Governance,
		&i.RoleSpecs,
		&i.CapabilityPacks,
		&i.SchedulePolicy,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveAgencyConstitutionByOffice = `-- name: GetActiveAgencyConstitutionByOffice :one
SELECT id, office_id, name, kind, is_active, org_intent, governance, role_specs, capability_packs, schedule_policy, metadata, updated_at, created_at
FROM agency_constitutions
WHERE office_id = ? AND is_active = 1
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetActiveAgencyConstitutionByOffice(ctx context.Context, officeID string) (AgencyConstitution, error) {
	row := q.queryRow(ctx, nil, getActiveAgencyConstitutionByOffice, officeID)
	var i AgencyConstitution
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Kind,
		&i.IsActive,
		&i.OrgIntent,
		&i.Governance,
		&i.RoleSpecs,
		&i.CapabilityPacks,
		&i.SchedulePolicy,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgencyConstitutionsByOffice = `-- name: ListAgencyConstitutionsByOffice :many
SELECT id, office_id, name, kind, is_active, org_intent, governance, role_specs, capability_packs, schedule_policy, metadata, updated_at, created_at
FROM agency_constitutions
WHERE office_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAgencyConstitutionsByOffice(ctx context.Context, officeID string) ([]AgencyConstitution, error) {
	rows, err := q.query(ctx, nil, listAgencyConstitutionsByOffice, officeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyConstitution{}
	for rows.Next() {
		var i AgencyConstitution
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.Name,
			&i.Kind,
			&i.IsActive,
			&i.OrgIntent,
			&i.Governance,
			&i.RoleSpecs,
			&i.CapabilityPacks,
			&i.SchedulePolicy,
			&i.Metadata,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deactivateAgencyConstitutionsByOffice = `-- name: DeactivateAgencyConstitutionsByOffice :exec
UPDATE agency_constitutions
SET
    is_active = 0,
    updated_at = strftime('%s', 'now')
WHERE office_id = ?
`

func (q *Queries) DeactivateAgencyConstitutionsByOffice(ctx context.Context, officeID string) error {
	_, err := q.exec(ctx, nil, deactivateAgencyConstitutionsByOffice, officeID)
	return err
}

const activateAgencyConstitution = `-- name: ActivateAgencyConstitution :one
UPDATE agency_constitutions
SET
    is_active = 1,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, office_id, name, kind, is_active, org_intent, governance, role_specs, capability_packs, schedule_policy, metadata, updated_at, created_at
`

func (q *Queries) ActivateAgencyConstitution(ctx context.Context, id string) (AgencyConstitution, error) {
	row := q.queryRow(ctx, nil, activateAgencyConstitution, id)
	var i AgencyConstitution
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Kind,
		&i.IsActive,
		&i.OrgIntent,
		&i.Governance,
		&i.RoleSpecs,
		&i.CapabilityPacks,
		&i.SchedulePolicy,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
