// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agency_offices.sql

package db

import "context"

const createAgencyOffice = `-- name: CreateAgencyOffice :one
INSERT INTO agency_offices (
    id,
    name,
    slug,
    mode,
    status,
    bus_driver,
    consensus_mode,
    workspace_path,
    shared_volume_path,
    redis_addr,
    ledger_driver,
    metadata,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, name, slug, mode, status, bus_driver, consensus_mode, workspace_path, shared_volume_path, redis_addr, ledger_driver, metadata, updated_at, created_at
`

type CreateAgencyOfficeParams struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	Slug             string `json:"slug"`
	Mode             string `json:"mode"`
	Status           string `json:"status"`
	BusDriver        string `json:"bus_driver"`
	ConsensusMode    string `json:"consensus_mode"`
	WorkspacePath    string `json:"workspace_path"`
	SharedVolumePath string `json:"shared_volume_path"`
	RedisAddr        string `json:"redis_addr"`
	LedgerDriver     string `json:"ledger_driver"`
	Metadata         string `json:"metadata"`
}

func (q *Queries) CreateAgencyOffice(ctx context.Context, arg CreateAgencyOfficeParams) (AgencyOffice, error) {
	row := q.queryRow(ctx, nil, createAgencyOffice,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Mode,
		arg.Status,
		arg.BusDriver,
		arg.ConsensusMode,
		arg.WorkspacePath,
		arg.SharedVolumePath,
		arg.RedisAddr,
		arg.LedgerDriver,
		arg.Metadata,
	)
	var i AgencyOffice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Mode,
		&i.Status,
		&i.BusDriver,
		&i.ConsensusMode,
		&i.WorkspacePath,
		&i.SharedVolumePath,
		&i.RedisAddr,
		&i.LedgerDriver,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgencyOfficeByID = `-- name: GetAgencyOfficeByID :one
SELECT id, name, slug, mode, status, bus_driver, consensus_mode, workspace_path, shared_volume_path, redis_addr, ledger_driver, metadata, updated_at, created_at
FROM agency_offices
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgencyOfficeByID(ctx context.Context, id string) (AgencyOffice, error) {
	row := q.queryRow(ctx, nil, getAgencyOfficeByID, id)
	var i AgencyOffice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Mode,
		&i.Status,
		&i.BusDriver,
		&i.ConsensusMode,
		&i.WorkspacePath,
		&i.SharedVolumePath,
		&i.RedisAddr,
		&i.LedgerDriver,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgencyOfficeBySlug = `-- name: GetAgencyOfficeBySlug :one
SELECT id, name, slug, mode, status, bus_driver, consensus_mode, workspace_path, shared_volume_path, redis_addr, ledger_driver, metadata, updated_at, created_at
FROM agency_offices
WHERE slug = ?
LIMIT 1
`

func (q *Queries) GetAgencyOfficeBySlug(ctx context.Context, slug string) (AgencyOffice, error) {
	row := q.queryRow(ctx, nil, getAgencyOfficeBySlug, slug)
	var i AgencyOffice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Mode,
		&i.Status,
		&i.BusDriver,
		&i.ConsensusMode,
		&i.WorkspacePath,
		&i.SharedVolumePath,
		&i.RedisAddr,
		&i.LedgerDriver,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgencyOffices = `-- name: ListAgencyOffices :many
SELECT id, name, slug, mode, status, bus_driver, consensus_mode, workspace_path, shared_volume_path, redis_addr, ledger_driver, metadata, updated_at, created_at
FROM agency_offices
ORDER BY created_at DESC
`

func (q *Queries) ListAgencyOffices(ctx context.Context) ([]AgencyOffice, error) {
	rows, err := q.query(ctx, nil, listAgencyOffices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyOffice{}
	for rows.Next() {
		var i AgencyOffice
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Mode,
			&i.Status,
			&i.BusDriver,
			&i.ConsensusMode,
			&i.WorkspacePath,
			&i.SharedVolumePath,
			&i.RedisAddr,
			&i.LedgerDriver,
			&i.Metadata,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgencyOfficesByStatus = `-- name: ListAgencyOfficesByStatus :many
SELECT id, name, slug, mode, status, bus_driver, consensus_mode, workspace_path, shared_volume_path, redis_addr, ledger_driver, metadata, updated_at, created_at
FROM agency_offices
WHERE status = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListAgencyOfficesByStatus(ctx context.Context, status string) ([]AgencyOffice, error) {
	rows, err := q.query(ctx, nil, listAgencyOfficesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyOffice{}
	for rows.Next() {
		var i AgencyOffice
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Mode,
			&i.Status,
			&i.BusDriver,
			&i.ConsensusMode,
			&i.WorkspacePath,
			&i.SharedVolumePath,
			&i.RedisAddr,
			&i.LedgerDriver,
			&i.Metadata,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgencyOfficeStatus = `-- name: UpdateAgencyOfficeStatus :one
UPDATE agency_offices
SET
    status = ?,
    metadata = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, name, slug, mode, status, bus_driver, consensus_mode, workspace_path, shared_volume_path, redis_addr, ledger_driver, metadata, updated_at, created_at
`

type UpdateAgencyOfficeStatusParams struct {
	Status   string `json:"status"`
	Metadata string `json:"metadata"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateAgencyOfficeStatus(ctx context.Context, arg UpdateAgencyOfficeStatusParams) (AgencyOffice, error) {
	row := q.queryRow(ctx, nil, updateAgencyOfficeStatus, arg.Status, arg.Metadata, arg.ID)
	var i AgencyOffice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Mode,
		&i.Status,
		&i.BusDriver,
		&i.ConsensusMode,
		&i.WorkspacePath,
		&i.SharedVolumePath,
		&i.RedisAddr,
		&i.LedgerDriver,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
