// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agency_agents.sql

package db

import (
	"context"
	"database/sql"
)

const createAgencyAgent = `-- name: CreateAgencyAgent :one
INSERT INTO agency_agents (
    id,
    office_id,
    constitution_id,
    parent_agent_id,
    identity_json,
    role_name,
    runtime_status,
    lifecycle_phase,
    workspace_path,
    inbox_channel,
    last_snapshot_id,
    last_wake_signal_id,
    capabilities_json,
    metadata,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, office_id, constitution_id, parent_agent_id, identity_json, role_name, runtime_status, lifecycle_phase, workspace_path, inbox_channel, last_snapshot_id, last_wake_signal_id, capabilities_json, metadata, updated_at, created_at
`

type CreateAgencyAgentParams struct {
	ID               string         `json:"id"`
	OfficeID         string         `json:"office_id"`
	ConstitutionID   sql.NullString `json:"constitution_id"`
	ParentAgentID    sql.NullString `json:"parent_agent_id"`
	IdentityJson     string         `json:"identity_json"`
	RoleName         string         `json:"role_name"`
	RuntimeStatus    string         `json:"runtime_status"`
	LifecyclePhase   string         `json:"lifecycle_phase"`
	WorkspacePath    string         `json:"workspace_path"`
	InboxChannel     string         `json:"inbox_channel"`
	LastSnapshotID   sql.NullString `json:"last_snapshot_id"`
	LastWakeSignalID sql.NullString `json:"last_wake_signal_id"`
	CapabilitiesJson string         `json:"capabilities_json"`
	Metadata         string         `json:"metadata"`
}

func (q *Queries) CreateAgencyAgent(ctx context.Context, arg CreateAgencyAgentParams) (AgencyAgent, error) {
	row := q.queryRow(ctx, nil, createAgencyAgent,
		arg.ID,
		arg.OfficeID,
		arg.ConstitutionID,
		arg.ParentAgentID,
		arg.IdentityJson,
		arg.RoleName,
		arg.RuntimeStatus,
		arg.LifecyclePhase,
		arg.WorkspacePath,
		arg.InboxChannel,
		arg.LastSnapshotID,
		arg.LastWakeSignalID,
		arg.CapabilitiesJson,
		arg.Metadata,
	)
	var i AgencyAgent
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.ConstitutionID,
		&i.ParentAgentID,
		&i.IdentityJson,
		&i.RoleName,
		&i.RuntimeStatus,
		&i.LifecyclePhase,
		&i.WorkspacePath,
		&i.InboxChannel,
		&i.LastSnapshotID,
		&i.LastWakeSignalID,
		&i.CapabilitiesJson,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgencyAgentByID = `-- name: GetAgencyAgentByID :one
SELECT id, office_id, constitution_id, parent_agent_id, identity_json, role_name, runtime_status, lifecycle_phase, workspace_path, inbox_channel, last_snapshot_id, last_wake_signal_id, capabilities_json, metadata, updated_at, created_at
FROM agency_agents
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgencyAgentByID(ctx context.Context, id string) (AgencyAgent, error) {
	row := q.queryRow(ctx, nil, getAgencyAgentByID, id)
	var i AgencyAgent
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.ConstitutionID,
		&i.ParentAgentID,
		&i.IdentityJson,
		&i.RoleName,
		&i.RuntimeStatus,
		&i.LifecyclePhase,
		&i.WorkspacePath,
		&i.InboxChannel,
		&i.LastSnapshotID,
		&i.LastWakeSignalID,
		&i.CapabilitiesJson,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgencyAgentsByOffice = `-- name: ListAgencyAgentsByOffice :many
SELECT id, office_id, constitution_id, parent_agent_id, identity_json, role_name, runtime_status, lifecycle_phase, workspace_path, inbox_channel, last_snapshot_id, last_wake_signal_id, capabilities_json, metadata, updated_at, created_at
FROM agency_agents
WHERE office_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListAgencyAgentsByOffice(ctx context.Context, officeID string) ([]AgencyAgent, error) {
	rows, err := q.query(ctx, nil, listAgencyAgentsByOffice, officeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyAgent{}
	for rows.Next() {
		var i AgencyAgent
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.ConstitutionID,
			&i.ParentAgentID,
			&i.IdentityJson,
			&i.RoleName,
			&i.RuntimeStatus,
			&i.LifecyclePhase,
			&i.WorkspacePath,
			&i.InboxChannel,
			&i.LastSnapshotID,
			&i.LastWakeSignalID,
			&i.CapabilitiesJson,
			&i.Metadata,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgencyChildAgents = `-- name: ListAgencyChildAgents :many
SELECT id, office_id, constitution_id, parent_agent_id, identity_json, role_name, runtime_status, lifecycle_phase, workspace_path, inbox_channel, last_snapshot_id, last_wake_signal_id, capabilities_json, metadata, updated_at, created_at
FROM agency_agents
WHERE parent_agent_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListAgencyChildAgents(ctx context.Context, parentAgentID string) ([]AgencyAgent, error) {
	rows, err := q.query(ctx, nil, listAgencyChildAgents, parentAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyAgent{}
	for rows.Next() {
		var i AgencyAgent
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.ConstitutionID,
			&i.ParentAgentID,
			&i.IdentityJson,
			&i.RoleName,
			&i.RuntimeStatus,
			&i.LifecyclePhase,
			&i.WorkspacePath,
			&i.InboxChannel,
			&i.LastSnapshotID,
			&i.LastWakeSignalID,
			&i.CapabilitiesJson,
			&i.Metadata,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgencyAgentRuntime = `-- name: UpdateAgencyAgentRuntime :one
UPDATE agency_agents
SET
    runtime_status = ?,
    lifecycle_phase = ?,
    last_snapshot_id = ?,
    last_wake_signal_id = ?,
    metadata = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, office_id, constitution_id, parent_agent_id, identity_json, role_name, runtime_status, lifecycle_phase, workspace_path, inbox_channel, last_snapshot_id, last_wake_signal_id, capabilities_json, metadata, updated_at, created_at
`

type UpdateAgencyAgentRuntimeParams struct {
	RuntimeStatus    string         `json:"runtime_status"`
	LifecyclePhase   string         `json:"lifecycle_phase"`
	LastSnapshotID   sql.NullString `json:"last_snapshot_id"`
	LastWakeSignalID sql.NullString `json:"last_wake_signal_id"`
	Metadata         string         `json:"metadata"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateAgencyAgentRuntime(ctx context.Context, arg UpdateAgencyAgentRuntimeParams) (AgencyAgent, error) {
	row := q.queryRow(ctx, nil, updateAgencyAgentRuntime,
		arg.RuntimeStatus,
		arg.LifecyclePhase,
		arg.LastSnapshotID,
		arg.LastWakeSignalID,
		arg.Metadata,
		arg.ID,
	)
	var i AgencyAgent
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.ConstitutionID,
		&i.ParentAgentID,
		&i.IdentityJson,
		&i.RoleName,
		&i.RuntimeStatus,
		&i.LifecyclePhase,
		&i.WorkspacePath,
		&i.InboxChannel,
		&i.LastSnapshotID,
		&i.LastWakeSignalID,
		&i.CapabilitiesJson,
		&i.Metadata,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
