// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agency_ledger.sql

package db

import (
	"context"
	"database/sql"
)

const appendAgencyLedgerEntry = `-- name: AppendAgencyLedgerEntry :one
INSERT INTO agency_ledger_entries (
    id,
    office_id,
    agent_id,
    entry_type,
    proposal_kind,
    snapshot_id,
    parent_entry_id,
    status,
    quorum_key,
    quorum_state,
    action_payload,
    observation_payload,
    commit_certificate,
    metadata,
    committed_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) RETURNING id, office_id, agent_id, entry_type, proposal_kind, snapshot_id, parent_entry_id, status, quorum_key, quorum_state, action_payload, observation_payload, commit_certificate, metadata, committed_at, created_at
`

type AppendAgencyLedgerEntryParams struct {
	ID                 string         `json:"id"`
	OfficeID           string         `json:"office_id"`
	AgentID            sql.NullString `json:"agent_id"`
	EntryType          string         `json:"entry_type"`
	ProposalKind       string         `json:"proposal_kind"`
	SnapshotID         sql.NullString `json:"snapshot_id"`
	ParentEntryID      sql.NullString `json:"parent_entry_id"`
	Status             string         `json:"status"`
	QuorumKey          string         `json:"quorum_key"`
	QuorumState        string         `json:"quorum_state"`
	ActionPayload      string         `json:"action_payload"`
	ObservationPayload string         `json:"observation_payload"`
	CommitCertificate  string         `json:"commit_certificate"`
	Metadata           string         `json:"metadata"`
	CommittedAt        sql.NullInt64  `json:"committed_at"`
}

func (q *Queries) AppendAgencyLedgerEntry(ctx context.Context, arg AppendAgencyLedgerEntryParams) (AgencyLedgerEntry, error) {
	row := q.queryRow(ctx, nil, appendAgencyLedgerEntry,
		arg.ID,
		arg.OfficeID,
		arg.AgentID,
		arg.EntryType,
		arg.ProposalKind,
		arg.SnapshotID,
		arg.ParentEntryID,
		arg.Status,
		arg.QuorumKey,
		arg.QuorumState,
		arg.ActionPayload,
		arg.ObservationPayload,
		arg.CommitCertificate,
		arg.Metadata,
		arg.CommittedAt,
	)
	var i AgencyLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.EntryType,
		&i.ProposalKind,
		&i.SnapshotID,
		&i.ParentEntryID,
		&i.Status,
		&i.QuorumKey,
		&i.QuorumState,
		&i.ActionPayload,
		&i.ObservationPayload,
		&i.CommitCertificate,
		&i.Metadata,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgencyLedgerEntryByID = `-- name: GetAgencyLedgerEntryByID :one
SELECT id, office_id, agent_id, entry_type, proposal_kind, snapshot_id, parent_entry_id, status, quorum_key, quorum_state, action_payload, observation_payload, commit_certificate, metadata, committed_at, created_at
FROM agency_ledger_entries
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgencyLedgerEntryByID(ctx context.Context, id string) (AgencyLedgerEntry, error) {
	row := q.queryRow(ctx, nil, getAgencyLedgerEntryByID, id)
	var i AgencyLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.EntryType,
		&i.ProposalKind,
		&i.SnapshotID,
		&i.ParentEntryID,
		&i.Status,
		&i.QuorumKey,
		&i.QuorumState,
		&i.ActionPayload,
		&i.ObservationPayload,
		&i.CommitCertificate,
		&i.Metadata,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgencyLedgerEntriesByOffice = `-- name: ListAgencyLedgerEntriesByOffice :many
SELECT id, office_id, agent_id, entry_type, proposal_kind, snapshot_id, parent_entry_id, status, quorum_key, quorum_state, action_payload, observation_payload, commit_certificate, metadata, committed_at, created_at
FROM agency_ledger_entries
WHERE office_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListAgencyLedgerEntriesByOffice(ctx context.Context, officeID string) ([]AgencyLedgerEntry, error) {
	rows, err := q.query(ctx, nil, listAgencyLedgerEntriesByOffice, officeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyLedgerEntry{}
	for rows.Next() {
		var i AgencyLedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.AgentID,
			&i.EntryType,
			&i.ProposalKind,
			&i.SnapshotID,
			&i.ParentEntryID,
			&i.Status,
			&i.QuorumKey,
			&i.QuorumState,
			&i.ActionPayload,
			&i.ObservationPayload,
			&i.CommitCertificate,
			&i.Metadata,
			&i.CommittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAgencyLedgerEntries = `-- name: ListPendingAgencyLedgerEntries :many
SELECT id, office_id, agent_id, entry_type, proposal_kind, snapshot_id, parent_entry_id, status, quorum_key, quorum_state, action_payload, observation_payload, commit_certificate, metadata, committed_at, created_at
FROM agency_ledger_entries
WHERE office_id = ?
  AND status IN ('proposed', 'pending', 'review')
ORDER BY created_at ASC
`

func (q *Queries) ListPendingAgencyLedgerEntries(ctx context.Context, officeID string) ([]AgencyLedgerEntry, error) {
	rows, err := q.query(ctx, nil, listPendingAgencyLedgerEntries, officeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgencyLedgerEntry{}
	for rows.Next() {
		var i AgencyLedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.AgentID,
			&i.EntryType,
			&i.ProposalKind,
			&i.SnapshotID,
			&i.ParentEntryID,
			&i.Status,
			&i.QuorumKey,
			&i.QuorumState,
			&i.ActionPayload,
			&i.ObservationPayload,
			&i.CommitCertificate,
			&i.Metadata,
			&i.CommittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const commitAgencyLedgerEntry = `-- name: CommitAgencyLedgerEntry :one
UPDATE agency_ledger_entries
SET
    status = ?,
    quorum_state = ?,
    commit_certificate = ?,
    metadata = ?,
    committed_at = ?
WHERE id = ?
RETURNING id, office_id, agent_id, entry_type, proposal_kind, snapshot_id, parent_entry_id, status, quorum_key, quorum_state, action_payload, observation_payload, commit_certificate, metadata, committed_at, created_at
`

type CommitAgencyLedgerEntryParams struct {
	Status            string        `json:"status"`
	QuorumState       string        `json:"quorum_state"`
	CommitCertificate string        `json:"commit_certificate"`
	Metadata          string        `json:"metadata"`
	CommittedAt       sql.NullInt64 `json:"committed_at"`
	ID                string        `json:"id"`
}

func (q *Queries) CommitAgencyLedgerEntry(ctx context.Context, arg CommitAgencyLedgerEntryParams) (AgencyLedgerEntry, error) {
	row := q.queryRow(ctx, nil, commitAgencyLedgerEntry,
		arg.Status,
		arg.QuorumState,
		arg.CommitCertificate,
		arg.Metadata,
		arg.CommittedAt,
		arg.ID,
	)
	var i AgencyLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.EntryType,
		&i.ProposalKind,
		&i.SnapshotID,
		&i.ParentEntryID,
		&i.Status,
		&i.QuorumKey,
		&i.QuorumState,
		&i.ActionPayload,
		&i.ObservationPayload,
		&i.CommitCertificate,
		&i.Metadata,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const rejectAgencyLedgerEntry = `-- name: RejectAgencyLedgerEntry :one
UPDATE agency_ledger_entries
SET
    status = 'rejected',
    quorum_state = ?,
    metadata = ?
WHERE id = ?
RETURNING id, office_id, agent_id, entry_type, proposal_kind, snapshot_id, parent_entry_id, status, quorum_key, quorum_state, action_payload, observation_payload, commit_certificate, metadata, committed_at, created_at
`

type RejectAgencyLedgerEntryParams struct {
	QuorumState string `json:"quorum_state"`
	Metadata    string `json:"metadata"`
	ID          string `json:"id"`
}

func (q *Queries) RejectAgencyLedgerEntry(ctx context.Context, arg RejectAgencyLedgerEntryParams) (AgencyLedgerEntry, error) {
	row := q.queryRow(ctx, nil, rejectAgencyLedgerEntry, arg.QuorumState, arg.Metadata, arg.ID)
	var i AgencyLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.AgentID,
		&i.EntryType,
		&i.ProposalKind,
		&i.SnapshotID,
		&i.ParentEntryID,
		&i.Status,
		&i.QuorumKey,
		&i.QuorumState,
		&i.ActionPayload,
		&i.ObservationPayload,
		&i.CommitCertificate,
		&i.Metadata,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}
