// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AcknowledgeAgencyWakeSignal(ctx context.Context, arg AcknowledgeAgencyWakeSignalParams) (AgencyWakeSignal, error)
	ActivateAgencyConstitution(ctx context.Context, id string) (AgencyConstitution, error)
	AppendAgencyLedgerEntry(ctx context.Context, arg AppendAgencyLedgerEntryParams) (AgencyLedgerEntry, error)
	CommitAgencyLedgerEntry(ctx context.Context, arg CommitAgencyLedgerEntryParams) (AgencyLedgerEntry, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateAgencyAgent(ctx context.Context, arg CreateAgencyAgentParams) (AgencyAgent, error)
	CreateAgencyConsensusVote(ctx context.Context, arg CreateAgencyConsensusVoteParams) (AgencyConsensusVote, error)
	CreateAgencyConstitution(ctx context.Context, arg CreateAgencyConstitutionParams) (AgencyConstitution, error)
	CreateAgencyContextSnapshot(ctx context.Context, arg CreateAgencyContextSnapshotParams) (AgencyContextSnapshot, error)
	CreateAgencyOffice(ctx context.Context, arg CreateAgencyOfficeParams) (AgencyOffice, error)
	CreateAgencySchedule(ctx context.Context, arg CreateAgencyScheduleParams) (AgencySchedule, error)
	CreateAgencyWakeSignal(ctx context.Context, arg CreateAgencyWakeSignalParams) (AgencyWakeSignal, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeactivateAgencyConstitutionsByOffice(ctx context.Context, officeID string) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetActiveAgencyConstitutionByOffice(ctx context.Context, officeID string) (AgencyConstitution, error)
	GetAgencyAgentByID(ctx context.Context, id string) (AgencyAgent, error)
	GetAgencyConstitutionByID(ctx context.Context, id string) (AgencyConstitution, error)
	GetAgencyConsensusVoteByID(ctx context.Context, id string) (AgencyConsensusVote, error)
	GetAgencyContextSnapshotByID(ctx context.Context, id string) (AgencyContextSnapshot, error)
	GetAgencyLedgerEntryByID(ctx context.Context, id string) (AgencyLedgerEntry, error)
	GetAgencyOfficeByID(ctx context.Context, id string) (AgencyOffice, error)
	GetAgencyOfficeBySlug(ctx context.Context, slug string) (AgencyOffice, error)
	GetAgencyScheduleByID(ctx context.Context, id string) (AgencySchedule, error)
	GetAgencyWakeSignalByID(ctx context.Context, id string) (AgencyWakeSignal, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetLatestAgencyContextSnapshotByOffice(ctx context.Context, officeID string) (AgencyContextSnapshot, error)
	ListAgencyAgentsByOffice(ctx context.Context, officeID string) ([]AgencyAgent, error)
	ListAgencyChildAgents(ctx context.Context, parentAgentID string) ([]AgencyAgent, error)
	ListAgencyConstitutionsByOffice(ctx context.Context, officeID string) ([]AgencyConstitution, error)
	ListAgencyConsensusVotesByLedgerEntry(ctx context.Context, ledgerEntryID string) ([]AgencyConsensusVote, error)
	ListAgencyConsensusVotesByQuorum(ctx context.Context, arg ListAgencyConsensusVotesByQuorumParams) ([]AgencyConsensusVote, error)
	ListAgencyContextSnapshotsByOffice(ctx context.Context, officeID string) ([]AgencyContextSnapshot, error)
	ListAgencyLedgerEntriesByOffice(ctx context.Context, officeID string) ([]AgencyLedgerEntry, error)
	ListAgencyOffices(ctx context.Context) ([]AgencyOffice, error)
	ListAgencyOfficesByStatus(ctx context.Context, status string) ([]AgencyOffice, error)
	ListAgencySchedulesByOffice(ctx context.Context, officeID string) ([]AgencySchedule, error)
	ListDueAgencySchedules(ctx context.Context, nextFireAt int64) ([]AgencySchedule, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListPendingAgencyLedgerEntries(ctx context.Context, officeID string) ([]AgencyLedgerEntry, error)
	ListPendingAgencyWakeSignalsByAgent(ctx context.Context, arg ListPendingAgencyWakeSignalsByAgentParams) ([]AgencyWakeSignal, error)
	ListPendingAgencyWakeSignalsByOffice(ctx context.Context, arg ListPendingAgencyWakeSignalsByOfficeParams) ([]AgencyWakeSignal, error)
	ListSessions(ctx context.Context) ([]Session, error)
	MarkAgencyWakeSignalDelivered(ctx context.Context, arg MarkAgencyWakeSignalDeliveredParams) (AgencyWakeSignal, error)
	RejectAgencyLedgerEntry(ctx context.Context, arg RejectAgencyLedgerEntryParams) (AgencyLedgerEntry, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
	UpdateAgencyAgentRuntime(ctx context.Context, arg UpdateAgencyAgentRuntimeParams) (AgencyAgent, error)
	UpdateAgencyOfficeStatus(ctx context.Context, arg UpdateAgencyOfficeStatusParams) (AgencyOffice, error)
	UpdateAgencyScheduleFireTimes(ctx context.Context, arg UpdateAgencyScheduleFireTimesParams) (AgencySchedule, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
